---
- name: Setup vim(RedHat)
  copy:
    src: vimrc
    dest: /etc/vimrc
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'RedHat'

- name: Setup vim(Ubuntu)
  copy:
    src: vimrc
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: '0644' 
  when: ansible_os_family == 'Debian'
